name: Build Executor
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile for iOS
        run: |
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          
          # This command finds EVERY .cpp and .mm file in your project
          find . -name "*.cpp" > files.txt
          find . -name "*.mm" >> files.txt
          
          clang++ -dynamiclib -arch arm64 \
          -isysroot "$SDK_PATH" \
          -miphoneos-version-min=14.0 \
          -fobjc-arc \
          -I. \
          -framework UIKit \
          -framework Metal \
          -framework Foundation \
          -framework QuartzCore \
          -framework CoreGraphics \
          -std=c++17 \
          -o MyExecutor.dylib $(cat files.txt)
      - name: Save Result
        uses: actions/upload-artifact@v4
        with:
          name: Final-Executor
          path: MyExecutor.dylib
