name: Build Executor
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile for iOS
        run: |
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)

          clang++ -dynamiclib -arch arm64 \
          -isysroot "$SDK_PATH" \
          -miphoneos-version-min=14.0 \
          -I. \
          -I./Include \
          -I./Methods \
          -I./Structures \
          -framework UIKit \
          -framework Metal \
          -framework Foundation \
          -framework QuartzCore \
          -std=c++17 \
          -fobjc-arc \
          -o MyExecutor.dylib \
          main.mm \
          imgui.cpp \
          imgui_draw.cpp \
          imgui_tables.cpp \
          imgui_widgets.cpp
      - name: Save Result
        uses: actions/upload-artifact@v4
        with:
          name: Final-Executor
          path: MyExecutor.dylib
